import type { CompareReport } from "./compare.js";
import { headlineVerdict } from "./report.js";

/** Escape a value for a Markdown table cell (pipes + newlines break tables). */
function cell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

function fmtUsd(n: number): string {
  const abs = Math.abs(n);
  const digits = abs > 0 && abs < 1 ? 6 : 2;
  return (n < 0 ? "-$" : "$") + abs.toFixed(digits);
}

function fmtSigned(n: number, digits: number, suffix = ""): string {
  const sign = n > 0 ? "+" : n < 0 ? "-" : "";
  return `${sign}${Math.abs(n).toFixed(digits)}${suffix}`;
}

function badge(statuses: string[] | undefined): string {
  if (!statuses || statuses.length === 0) return "BROKEN";
  return statuses.join(", ");
}

/**
 * Render a comparison as GitHub-flavored Markdown — suitable for pasting into a
 * pull-request comment or a CI job summary. Self-contained, no images. Changed
 * outputs go into collapsible <details> blocks so the comment stays scannable.
 */
export function renderMarkdown(report: CompareReport): string {
  const s = report.summary;
  const lines: string[] = [];

  lines.push(`# Lockstep report`);
  lines.push("");
  lines.push(`**${cell(headlineVerdict(report))}**`);
  lines.push("");
  lines.push(
    `\`${cell(report.aTargetId)}\` (${cell(report.aModel)}) vs ` +
      `\`${cell(report.bTargetId)}\` (${cell(report.bModel)}) — ` +
      `drift threshold ${(report.similarityThreshold * 100).toFixed(0)}%`
  );
  if (report.generatedAt) lines.push(`\n_generated ${cell(report.generatedAt)}_`);
  lines.push("");

  lines.push(`| ok | drifted | broken | cheaper | pricier | faster | slower |`);
  lines.push(`|---:|---:|---:|---:|---:|---:|---:|`);
  lines.push(
    `| ${s.ok} | ${s.drifted} | ${s.broken} | ${s.cheaper} | ${s.pricier} | ${s.faster} | ${s.slower} |`
  );
  lines.push("");
  lines.push(
    `Total cost: **${fmtUsd(s.totalCostA)}** (A) → **${fmtUsd(s.totalCostB)}** (B)`
  );
  lines.push("");

  lines.push(`## Cases`);
  lines.push("");
  lines.push(`| case | similarity | Δ cost | Δ latency | status |`);
  lines.push(`|---|---:|---:|---:|---|`);
  for (const p of report.pairs) {
    const c = p.cell;
    const sim = c ? `${(c.similarity * 100).toFixed(0)}%` : "—";
    const dCost = c ? fmtSigned(c.costDelta, 6, "") : "—";
    const dLat = c ? fmtSigned(c.latencyDelta, 0, "ms") : "—";
    lines.push(
      `| \`${cell(p.caseId)}#${p.inputIndex}\` | ${sim} | ${dCost} | ${dLat} | ${cell(badge(c?.statuses))} |`
    );
  }
  lines.push("");

  const changed = report.pairs.filter(
    (p) => !p.cell || !(p.cell.statuses.length === 1 && p.cell.statuses[0] === "OK")
  );
  if (changed.length > 0) {
    lines.push(`## Changed outputs`);
    lines.push("");
    for (const p of changed) {
      lines.push(
        `<details><summary><code>${cell(p.caseId)}#${p.inputIndex}</code> — ${cell(badge(p.cell?.statuses))}</summary>`
      );
      lines.push("");
      lines.push(`**A (${cell(report.aTargetId)}):**`);
      lines.push("");
      lines.push("```");
      lines.push((p.a?.output ?? "(missing)").slice(0, 4000));
      lines.push("```");
      lines.push("");
      lines.push(`**B (${cell(report.bTargetId)}):**`);
      lines.push("");
      lines.push("```");
      lines.push((p.b?.output ?? "(missing)").slice(0, 4000));
      lines.push("```");
      lines.push("");
      lines.push(`</details>`);
      lines.push("");
    }
  }

  lines.push(`---`);
  lines.push(`<sub>Generated by [Lockstep](https://github.com/arwenizEr/lockstep).</sub>`);
  lines.push("");
  return lines.join("\n");
}
