import type { CompareReport } from "./compare.js";
import { headlineVerdict } from "./report.js";

/** Escape a value for a Markdown table cell (pipes + newlines break tables). */
function cell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

function fmtUsd(n: number): string {
  const abs = Math.abs(n);
  const digits = abs > 0 && abs < 1 ? 6 : 2;
  return (n < 0 ? "-$" : "$") + abs.toFixed(digits);
}

function fmtSigned(n: number, digits: number, suffix = ""): string {
  const sign = n > 0 ? "+" : n < 0 ? "-" : "";
  return `${sign}${Math.abs(n).toFixed(digits)}${suffix}`;
}

function badge(statuses: string[] | undefined): string {
  if (!statuses || statuses.length === 0) return "BROKEN";
  return statuses.join(", ");
}

/** Compact "which side won" verdict for the Cases table (mirrors the HTML report). */
function bestTarget(p: CompareReport["pairs"][number]): string {
  if (!p.cell || !p.a || !p.b) {
    if (p.a && !p.b) return "A (B missing)";
    if (p.b && !p.a) return "B (A missing)";
    return "—";
  }
  const c = p.cell;
  if (c.broken) {
    const aOk = p.a.status === "OK" && p.a.assertionsPass !== false;
    const bOk = p.b.status === "OK" && p.b.assertionsPass !== false;
    if (aOk && !bOk) return "A (B broke)";
    if (bOk && !aOk) return "B (A broke)";
    return "neither";
  }
  const aj = p.a.judge?.score;
  const bj = p.b.judge?.score;
  if (aj !== undefined && bj !== undefined && Math.abs(aj - bj) > 0.05) {
    return aj > bj ? "A (judge)" : "B (judge)";
  }
  if (c.costDelta < 0) return "B (cheaper)";
  if (c.costDelta > 0) return "A (cheaper)";
  if (c.latencyDelta < 0) return "B (faster)";
  if (c.latencyDelta > 0) return "A (faster)";
  return "tie";
}

/**
 * Render a comparison as GitHub-flavored Markdown — suitable for pasting into a
 * pull-request comment or a CI job summary. Self-contained, no images. Changed
 * outputs go into collapsible <details> blocks so the comment stays scannable.
 */
export function renderMarkdown(report: CompareReport): string {
  const s = report.summary;
  const lines: string[] = [];

  lines.push(`# Lockstep report`);
  lines.push("");
  lines.push(`**${cell(headlineVerdict(report))}**`);
  lines.push("");
  lines.push(
    `\`${cell(report.aTargetId)}\` (${cell(report.aModel)}) vs ` +
      `\`${cell(report.bTargetId)}\` (${cell(report.bModel)}) — ` +
      `drift threshold ${(report.similarityThreshold * 100).toFixed(0)}%`
  );
  if (report.generatedAt) lines.push(`\n_generated ${cell(report.generatedAt)}_`);
  lines.push("");

  lines.push(`| ok | drifted | broken | cheaper | pricier | faster | slower |`);
  lines.push(`|---:|---:|---:|---:|---:|---:|---:|`);
  lines.push(
    `| ${s.ok} | ${s.drifted} | ${s.broken} | ${s.cheaper} | ${s.pricier} | ${s.faster} | ${s.slower} |`
  );
  lines.push("");
  lines.push(
    `Total cost: **${fmtUsd(s.totalCostA)}** (A) → **${fmtUsd(s.totalCostB)}** (B)`
  );
  lines.push("");

  lines.push(`## Cases`);
  lines.push("");
  lines.push(`| case | similarity | Δ cost | Δ latency | status | best |`);
  lines.push(`|---|---:|---:|---:|---|---|`);
  for (const p of report.pairs) {
    const c = p.cell;
    const sim = c ? `${(c.similarity * 100).toFixed(0)}%` : "—";
    const dCost = c ? fmtSigned(c.costDelta, 6, "") : "—";
    const dLat = c ? fmtSigned(c.latencyDelta, 0, "ms") : "—";
    lines.push(
      `| \`${cell(p.caseId)}#${p.inputIndex}\` | ${sim} | ${dCost} | ${dLat} | ${cell(badge(c?.statuses))} | ${cell(bestTarget(p))} |`
    );
  }
  lines.push("");

  const changed = report.pairs.filter(
    (p) => !p.cell || !(p.cell.statuses.length === 1 && p.cell.statuses[0] === "OK")
  );
  if (changed.length > 0) {
    lines.push(`## Changed outputs`);
    lines.push("");
    for (const p of changed) {
      lines.push(
        `<details><summary><code>${cell(p.caseId)}#${p.inputIndex}</code> — ${cell(badge(p.cell?.statuses))}</summary>`
      );
      lines.push("");
      lines.push(`**A (${cell(report.aTargetId)}):**`);
      lines.push("");
      lines.push("```");
      lines.push((p.a?.output ?? "(missing)").slice(0, 4000));
      lines.push("```");
      lines.push("");
      lines.push(`**B (${cell(report.bTargetId)}):**`);
      lines.push("");
      lines.push("```");
      lines.push((p.b?.output ?? "(missing)").slice(0, 4000));
      lines.push("```");
      lines.push("");
      if (p.a?.judge || p.b?.judge) {
        const fmtJudge = (j?: { score: number; reason: string }) =>
          j ? `${j.score.toFixed(2)} — ${cell(j.reason)}` : "—";
        lines.push(`_judge — A: ${fmtJudge(p.a?.judge)} · B: ${fmtJudge(p.b?.judge)}_`);
        lines.push("");
      }
      lines.push(`</details>`);
      lines.push("");
    }
  }

  lines.push(`---`);
  lines.push(`<sub>Generated by [Lockstep](https://github.com/arwenizEr/lockstep).</sub>`);
  lines.push("");
  return lines.join("\n");
}
